name: Build and Tests
on:
  pull_request:
    branches:
    - development

jobs:
  test:
    name: Run in Mac 
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Entering in project
        run: cd ChallengeAnimalUser

      - name: Unit tests
        run: fastlane tests
