configurations:
    - sources:
        - /Users/Mirazev/Desktop/ChallengeAnimalUser/ChallengeAnimalUser/ChallengeAnimalUser/Presentation
      templates:
        - /Users/Mirazev/Desktop/ChallengeAnimalUser/ChallengeAnimalUser/FramesStencils/autoViewConstraints.stencil
      output: /Users/Mirazev/Desktop/ChallengeAnimalUser/ChallengeAnimalUser/ChallengeAnimalUser/Presentation/View


#    - sources:
#        - /Users/Mirazev/Desktop/ChallengeAnimalUser/ChallengeAnimalUser/ChallengeAnimalUser/Model
#      templates:
#        - /Users/Mirazev/Desktop/ChallengeAnimalUser/ChallengeAnimalUser/FramesStencils/autoEquatable.stencil
#      output: /Users/Mirazev/Desktop/ChallengeAnimalUser/ChallengeAnimalUser/ChallengeAnimalUser/Model
